[package]
name = "tedbot-rs"
version = "0.1.0"
edition = "2021"
description = "Rust discord bot."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/tedbot-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["discord", "bot"]
publish = false

[dependencies]
serde = "1.0.133"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "parking_lot"] }
toml = "0.5.8"
tracing = "0.1.29"

[dependencies.serenity]
version = "0.10.9"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]

[dependencies.tracing-subscriber]
version = "0.3.6"
default-features = false
features = ["std", "env-filter", "fmt", "ansi", "smallvec", "parking_lot"]

[dev-dependencies]
wiremock = "0.5.10"
# strip = "symbols"

[profile.dev]
debug = 0

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
