[package]
name = "tedbot-rs"
version = "0.1.0"
edition = "2021"
description = "Rust discord bot."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/tedbot-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["discord", "bot"]
publish = false

[features]
default = []

[dependencies]
bincode = "2.0.0-beta.2"
dotenv = { version = "0.15.0", optional = true }
lazy_static = "1.4.0"
nom = "7.1.0"
sled = { version = "0.34.7", features = ["compression"] }
tracing = "0.1.29"
chrono = "0.4.19"

[dependencies.serenity]
version = "0.10.10"
default-features = false
features = ["cache", "client", "gateway", "rustls_backend", "model", "unstable_discord_api"]

[dependencies.tokio]
version = "1.16.1"
default-features = false
features = ["rt-multi-thread", "macros", "parking_lot"]

[dependencies.tracing-subscriber]
version = "0.3.7"
default-features = false
features = ["std", "env-filter", "fmt", "ansi", "smallvec", "parking_lot"]

[dev-dependencies]
wiremock = "0.5.10"

[profile.dev]
debug = 0

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
# strip = "symbols"
