[package]
name = "tedbot-rs"
version = "0.1.0"
edition = "2021"
description = "Rust discord bot."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/tedbot-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["discord", "bot"]
publish = false

[features]
default = []

[dependencies]
tracing = "0.1.29"
dotenv = { version = "0.15.0", optional = true }

[dependencies.tokio]
version = "1.15.0"
default-features = false
features = ["rt-multi-thread", "macros", "parking_lot"]

[dependencies.serenity]
version = "0.10.9"
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]

[dependencies.tracing-subscriber]
version = "0.3.6"
default-features = false
features = ["std", "env-filter", "fmt", "ansi", "smallvec", "parking_lot"]

[dev-dependencies]
wiremock = "0.5.10"

[profile.dev]
debug = 0

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
# strip = "symbols"
